# Generated by Django 5.1 on 2024-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador del sistema'), ('encargado_tienda', 'Encargado de Tienda'), ('bodeguero', 'Bodeguero'), ('encargado_logistica', 'Encargado de Logística'), ('Prueba', 'test')], max_length=20),
        ),
    ]
