# Generated by Django 5.1 on 2024-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTests',
            fields=[
                ('Id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('Nombre', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=100)),
                ('Stock', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Producto Tests',
            },
        ),
    ]
