# Generated by Django 5.1 on 2024-09-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIngresosTests',
            fields=[
                ('Id_Ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('Skus', models.ManyToManyField(to='inventory.productotests')),
            ],
        ),
    ]
