# Generated by Django 5.1 on 2024-09-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingresotest_detalleingresotest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialingresostests',
            name='Skus',
        ),
        migrations.AlterField(
            model_name='historialingresostests',
            name='Id_Ingreso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.ingresotest'),
        ),
    ]
